#!/usr/bin/env python3
"""Build reports/cdcnn-experiment-review.pptx from the review script.

Slide content is written here rather than parsed from the markdown, so wording
can differ where a slide needs to be terser than the speaker script. Figures come
from reports/figures/, regenerated by scripts/make_report_figures.py.
"""
from __future__ import annotations

from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.util import Emu, Inches, Pt

ROOT = Path(__file__).resolve().parents[1]
FIG = ROOT / "reports" / "figures"
OUT = ROOT / "reports" / "cdcnn-experiment-review.pptx"

NAVY = RGBColor(0x1E, 0x27, 0x61)
ICE = RGBColor(0xCA, 0xDC, 0xFC)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
INK = RGBColor(0x1A, 0x1A, 0x1A)
MUTED = RGBColor(0x5A, 0x5A, 0x66)
ACCENT = RGBColor(0xC0, 0x39, 0x2B)
HEAD_FONT, BODY_FONT = "Cambria", "Calibri"
W, H = Inches(13.333), Inches(7.5)
MARGIN = Inches(0.75)


def textbox(slide, x, y, w, h, *, align=PP_ALIGN.LEFT, anchor=MSO_ANCHOR.TOP):
    box = slide.shapes.add_textbox(x, y, w, h)
    tf = box.text_frame
    tf.word_wrap = True
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0
    tf.vertical_anchor = anchor
    tf.paragraphs[0].alignment = align
    return tf


def run(par, text, *, size=16, bold=False, color=INK, font=BODY_FONT, italic=False):
    r = par.add_run()
    r.text = text
    r.font.size = Pt(size)
    r.font.bold = bold
    r.font.italic = italic
    r.font.color.rgb = color
    r.font.name = font
    return r


def blank(prs, dark=False):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    if dark:
        bg = slide.shapes.add_shape(1, 0, 0, W, H)
        bg.fill.solid(); bg.fill.fore_color.rgb = NAVY
        bg.line.fill.background(); bg.shadow.inherit = False
    return slide


def title_slide(prs, title, subtitle, meta):
    slide = blank(prs, dark=True)
    tf = textbox(slide, MARGIN, Inches(2.3), W - 2 * MARGIN, Inches(2.2))
    run(tf.paragraphs[0], title, size=44, bold=True, color=WHITE, font=HEAD_FONT)
    p = tf.add_paragraph(); p.space_before = Pt(14)
    run(p, subtitle, size=20, color=ICE)
    p = tf.add_paragraph(); p.space_before = Pt(26)
    run(p, meta, size=13, color=ICE)
    return slide


def content_slide(prs, title, kicker=None):
    slide = blank(prs)
    tf = textbox(slide, MARGIN, Inches(0.55), W - 2 * MARGIN, Inches(0.9))
    run(tf.paragraphs[0], title, size=34, bold=True, color=NAVY, font=HEAD_FONT)
    if kicker:
        p = tf.add_paragraph(); p.space_before = Pt(6)
        run(p, kicker, size=15, color=MUTED, italic=True)
    return slide


def bullets(slide, items, *, top=Inches(1.9), left=MARGIN, width=None, size=17):
    width = width or (W - 2 * MARGIN)
    tf = textbox(slide, left, top, width, H - top - Inches(0.7))
    for i, item in enumerate(items):
        text, *rest = item if isinstance(item, tuple) else (item,)
        style = rest[0] if rest else "plain"
        par = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        par.space_after = Pt(12)
        if style == "head":
            run(par, text, size=size + 2, bold=True, color=NAVY, font=HEAD_FONT)
        elif style == "key":
            run(par, "▍ ", size=size, bold=True, color=ACCENT)
            run(par, text, size=size, bold=True, color=INK)
        elif style == "sub":
            par.level = 1
            run(par, text, size=size - 3, color=MUTED)
        else:
            run(par, "· ", size=size, color=ICE)
            run(par, text, size=size, color=INK)
    return tf


def table_slide(prs, title, headers, rows, *, kicker=None, note=None,
                col_widths=None, highlight=(), size=13):
    slide = content_slide(prs, title, kicker)
    top = Inches(1.95)
    height = Inches(0.42) * (len(rows) + 1)
    shape = slide.shapes.add_table(len(rows) + 1, len(headers), MARGIN, top,
                                   W - 2 * MARGIN, height)
    table = shape.table
    table.first_row = True
    if col_widths:
        total = W - 2 * MARGIN
        for i, frac in enumerate(col_widths):
            table.columns[i].width = Emu(int(total * frac))
    for c, head in enumerate(headers):
        cell = table.cell(0, c)
        cell.text = head
        par = cell.text_frame.paragraphs[0]
        par.alignment = PP_ALIGN.LEFT if c == 0 else PP_ALIGN.RIGHT
        par.runs[0].font.size = Pt(size)
        par.runs[0].font.bold = True
        par.runs[0].font.color.rgb = WHITE
        par.runs[0].font.name = BODY_FONT
        cell.fill.solid(); cell.fill.fore_color.rgb = NAVY
    for r, row in enumerate(rows, start=1):
        for c, value in enumerate(row):
            cell = table.cell(r, c)
            # an empty string leaves the paragraph without a run to style
            cell.text = str(value) if str(value) else "\u00a0"
            par = cell.text_frame.paragraphs[0]
            par.alignment = PP_ALIGN.LEFT if c == 0 else PP_ALIGN.RIGHT
            par.runs[0].font.size = Pt(size)
            par.runs[0].font.name = BODY_FONT
            strong = (r - 1) in highlight
            par.runs[0].font.bold = strong
            par.runs[0].font.color.rgb = ACCENT if strong else INK
            cell.fill.solid()
            cell.fill.fore_color.rgb = RGBColor(0xF2, 0xF5, 0xFC) if r % 2 else WHITE
    if note:
        tf = textbox(slide, MARGIN, top + height + Inches(0.28), W - 2 * MARGIN, Inches(1.0))
        run(tf.paragraphs[0], note, size=13, color=MUTED)
    return slide


def figure_slide(prs, title, image, points, *, kicker=None):
    slide = content_slide(prs, title, kicker)
    from PIL import Image
    with Image.open(image) as im:
        ratio = im.height / im.width
    width = Inches(8.0)
    height = Emu(int(width * ratio))
    max_h = Inches(4.9)
    if height > max_h:
        height = max_h
        width = Emu(int(height / ratio))
    slide.shapes.add_picture(str(image), MARGIN, Inches(2.0), width=width, height=height)
    text_left = MARGIN + width + Inches(0.4)
    bullets(slide, points, top=Inches(2.05), left=text_left,
            width=W - text_left - MARGIN, size=15)
    return slide


def stat_slide(prs, title, stats, points, *, kicker=None):
    slide = content_slide(prs, title, kicker)
    gap = Inches(0.35)
    card_w = (W - 2 * MARGIN - gap * (len(stats) - 1)) / len(stats)
    for i, (value, label) in enumerate(stats):
        x = MARGIN + i * (card_w + gap)
        card = slide.shapes.add_shape(5, Emu(int(x)), Inches(1.95), Emu(int(card_w)), Inches(1.75))
        card.fill.solid(); card.fill.fore_color.rgb = RGBColor(0xF2, 0xF5, 0xFC)
        card.line.color.rgb = ICE; card.shadow.inherit = False
        tf = textbox(slide, Emu(int(x)), Inches(2.15), Emu(int(card_w)), Inches(1.4),
                     align=PP_ALIGN.CENTER)
        run(tf.paragraphs[0], value, size=40, bold=True, color=NAVY, font=HEAD_FONT)
        p = tf.add_paragraph(); p.alignment = PP_ALIGN.CENTER; p.space_before = Pt(4)
        run(p, label, size=13, color=MUTED)
    bullets(slide, points, top=Inches(4.15))
    return slide


def closing_slide(prs, title, items):
    slide = blank(prs, dark=True)
    tf = textbox(slide, MARGIN, Inches(0.8), W - 2 * MARGIN, Inches(1.0))
    run(tf.paragraphs[0], title, size=36, bold=True, color=WHITE, font=HEAD_FONT)
    body = textbox(slide, MARGIN, Inches(2.0), W - 2 * MARGIN, Inches(4.6))
    for i, (head, detail) in enumerate(items):
        par = body.paragraphs[0] if i == 0 else body.add_paragraph()
        par.space_after = Pt(6)
        run(par, f"{i + 1}. ", size=18, bold=True, color=ICE, font=HEAD_FONT)
        run(par, head, size=18, bold=True, color=WHITE, font=HEAD_FONT)
        sub = body.add_paragraph(); sub.space_after = Pt(16)
        run(sub, f"    {detail}", size=14, color=ICE)
    return slide


def build() -> None:
    prs = Presentation()
    prs.slide_width, prs.slide_height = W, H

    title_slide(prs, "CDCNN 復現實驗回顧",
                "在嚴格 source-only 協定下復現對比域泛化卷積神經網路",
                "UCI Gas Sensor Array Drift · 11 輪實驗 · 約 200 個凍結檢查點 · 2026-09")

    # --- literature review -------------------------------------------------
    content = content_slide(prs, "文獻回顧：問題與既有方法",
                            "Sensors and Actuators A 372 (2024) 115314")
    bullets(content, [
        ("感測器漂移", "head"),
        "MOS 氣體感測器因老化、中毒與環境波動，對同一氣體的響應隨時間偏移",
        "電子鼻的長期辨識準確率與壽命因此大幅下降",
        ("既有方法的共同限制", "head"),
        "PCA-SVM、LDA-SVM：手工特徵與線性／核轉換，無法擬合非線性長期漂移",
        "SVM-GFK 等流形學習：仍需依賴目標域資料",
        "TDACNN：4 個分類器的集成，54 K 參數，測試時仍需存取源域",
    ])

    figure_slide(prs, "文獻回顧：域泛化與對比學習的概念", FIG / "paper_fig1_concept.png",
                 [("(a) 一般深度學習", "key"),
                  "訓練與測試來自同一分布 P",
                  ("(b) 域泛化", "key"),
                  "多個訓練域 P1…Pn，測試域從未被看過",
                  ("(c) 對比學習", "key"),
                  "同標籤樣本在單位球上被拉近，異標籤被推開"],
                 kicker="論文 Fig. 1")

    figure_slide(prs, "文獻回顧：CDCNN 架構", FIG / "paper_fig2_framework.png",
                 [("五個 ResNet 區塊，Conv1d", "key"),
                  "特徵生成插在第 3 與第 4 區塊之間",
                  ("對比損失接在 FC128 之前的 z_f", "key"),
                  "分類頭僅 0.77 K 參數",
                  "L2 loss 約束兩分支輸出一致"],
                 kicker="論文 Fig. 2 — 我們的實作差異見後續")

    slide = content_slide(prs, "文獻回顧：機制① 資料擴充", "論文 Fig. S5 與 Fig. 4")
    slide.shapes.add_picture(str(FIG / "paper_figS5_augment.png"), MARGIN, Inches(1.95),
                             width=Inches(5.6))
    slide.shapes.add_picture(str(FIG / "paper_fig4_aug_pca.png"), Inches(7.0), Inches(1.75),
                             height=Inches(4.3))
    tf = textbox(slide, MARGIN, Inches(4.5), Inches(5.6), Inches(2.2))
    run(tf.paragraphs[0], "混合兩個樣本的均值與變異數，生成新的高斯分布後抽樣雜訊疊加到原訊號。",
        size=15)
    par = tf.add_paragraph(); par.space_before = Pt(10)
    run(par, "右圖：相較白高斯雜訊與常數雜訊，CDCNN 的擴充在 PCA 空間產生明顯更大的分散。",
        size=15, color=MUTED)

    slide = content_slide(prs, "文獻回顧：機制② 特徵生成", "論文 Fig. S4(b) 與 Fig. 5")
    slide.shapes.add_picture(str(FIG / "paper_figS4_blocks.png"), MARGIN, Inches(2.0),
                             width=Inches(5.9))
    slide.shapes.add_picture(str(FIG / "paper_fig5_featgen.png"), Inches(7.1), Inches(2.0),
                             width=Inches(5.5))
    tf = textbox(slide, MARGIN, Inches(4.7), Inches(5.9), Inches(2.0))
    run(tf.paragraphs[0], "最大池化與最近鄰上採樣把隱特徵拆成高頻與低頻，替換低頻的風格統計量後重組。",
        size=15)
    par = tf.add_paragraph(); par.space_before = Pt(10)
    run(par, "右圖：橘色為生成特徵，覆蓋範圍遠大於原始特徵——這是他們宣稱能模擬未見漂移的依據。",
        size=15, color=MUTED)

    content = content_slide(prs, "文獻回顧：機制③ 監督式對比學習")
    bullets(content, [
        ("聯合損失", "head"),
        "L = L_ce + λ_MSE · L_MSE + λ_con · L_con",
        "L_ce 維持分類能力；L_MSE 確保風格轉換前後標籤一致；L_con 整理特徵空間",
        ("論文的消融（CDWC = 移除對比學習）", "head"),
        ("0.6705 → 0.7230，對比學習貢獻 +5.25%", "key"),
        "其中最大的單類改善是 Toluene：0.27 → 0.92",
        ("論文未提供 τ、λ_con 與投影維度的數值", "sub"),
    ])

    figure_slide(prs, "文獻回顧：論文的方法比較", FIG / "paper_fig6_comparison.png",
                 [("CDCNN 0.7230，所有比較方法中最高", "key"),
                  "TDACNN 0.7221 次之，但需 54 K 參數與集成",
                  "CDWC（移除對比學習）0.6705",
                  "ResNet 骨幹 0.6344",
                  ("多數深度網路（VGG、GoogLeNet）在此資料集低於 0.25", "sub")],
                 kicker="論文 Fig. 6")

    table_slide(prs, "文獻回顧：論文宣稱的表現",
                ["方法", "平均準確率", "備註"],
                [["CDCNN（本論文）", "0.7230", "Target-free，0.77 K 參數"],
                 ["TDACNN", "0.7221", "集成 4 分類器，54 K 參數"],
                 ["PCA-SVM", "0.6860", ""],
                 ["DBNs", "0.6665", ""],
                 ["SVM-GFK", "0.6400", ""],
                 ["ResNet（骨幹）", "0.6344", ""],
                 ["CDWC（移除對比學習）", "0.6705", "對比學習貢獻 +5.25%"]],
                kicker="Batch 1 訓練、Batch 2–10 測試",
                col_widths=[0.42, 0.22, 0.36], highlight=(0, 6),
                note="關鍵：論文自己的消融把 +5.25% 歸因於對比學習，並指出 Toluene 從 0.27 提升到 0.92。")

    # --- our protocol and baseline ----------------------------------------
    content = content_slide(prs, "我們的實驗協定", "比論文更嚴格，且全程可稽核")
    bullets(content, [
        ("只用 Batch 1（445 筆）做訓練、正規化擬合、交叉驗證與所有選擇", "key"),
        ("所有檢查點凍結並雜湊後，目標批次才各載入一次", "key"),
        "五個固定種子、100 epochs、SGD、StepLR、batch 64",
        "每次執行寫入獨立目錄，附洩漏稽核；違規即失敗",
        "指標：target mean＝九個目標批次準確率的未加權平均（與論文相同）",
    ])

    table_slide(prs, "正式的四階段結果",
                ["Stage", "CV", "Target", "B2", "B4", "B6", "B8", "B10", "論文"],
                [["B0 基線", "0.978", "0.410", "0.74", "0.50", "0.48", "0.20", "0.29", "0.634"],
                 ["A1 +增強", "0.980", "0.372", "0.73", "0.49", "0.42", "0.13", "0.30", "—"],
                 ["A2 +特徵生成", "0.982", "0.397", "0.77", "0.49", "0.42", "0.17", "0.31", "0.670"],
                 ["A3 +對比學習", "0.968", "0.460", "0.89", "0.58", "0.41", "0.17", "0.42", "0.723"]],
                col_widths=[0.22, 0.1, 0.11, 0.09, 0.09, 0.09, 0.09, 0.09, 0.12],
                highlight=(3,),
                note="四個 stage 的 Batch 1 CV 都在 0.97–0.98：問題不在擬合，在泛化。A1 與 A2 比基線還差，順序沒有重現論文。")

    # --- the ablation ------------------------------------------------------
    table_slide(prs, "第一個發現：A3 的增益不是對比學習",
                ["拆解出的成分", "效果", "改善的種子"],
                [["LayerNorm 取代 BatchNorm", "+0.0845", "5/5"],
                 ["硬性界限 + 梯度裁剪", "−0.0022", "1/5"],
                 ["增強 + 特徵生成", "−0.0328", "0/5"],
                 ["對比損失", "+0.0029", "4/5"]],
                kicker="v6.3 一次給了 A3 四樣東西，把它們拆開量",
                col_widths=[0.5, 0.25, 0.25], highlight=(0,),
                note="BatchNorm 把 Batch 1 的統計量套到漂移資料上；LayerNorm 逐樣本正規化。增益最大的正是漂移最嚴重的批次。")

    content = content_slide(prs, "對照論文後的轉折")
    bullets(content, [
        ("論文的純 ResNet 基線 0.6344，贏過我們當時所有 stage（最高 0.4922）", "key"),
        "差距在 CDCNN 三個元件「之外」——不是方法不夠，是上游有問題",
        ("讀完全文與補充資料後找到三個未聲明的差異：", "head"),
        "對比損失應接在 FC128 之前、且沒有可學的投影 head",
        "Eq. (16) 除以的是變異數而非標準差；Block 5 內層為 512 寬",
        "論文本身亦有矛盾處：統計量維度前後不一致、Table 2 有兩處計數錯誤",
    ])

    # --- the real lever ----------------------------------------------------
    stat_slide(prs, "突破：逐樣本輸入正規化",
               [("+0.109", "逐樣本輸入正規化"), ("+0.085", "LayerNorm"),
                ("+0.149", "兩者合併"), ("0/5", "壓極端值（clip）有效的種子")],
               [("在 Batch 1 的 scaler 下，Batch 2 有 |z| ≈ 1.5×10⁴ 的極端值", "key"),
                "但 signed-log 與 clip 都無效——有效的是移除每個樣本自己的偏移與增益",
                "兩者皆為 5/5 種子改善"])

    table_slide(prs, "進步從哪裡來",
                ["模型", "Target mean"],
                [["A1 增強", "0.372"], ["A2 特徵生成", "0.397"], ["B0 基線", "0.410"],
                 ["A3 完整 CDCNN（v6.3）", "0.460"], ["+ LayerNorm", "0.492"],
                 ["+ 逐樣本輸入", "0.557"], ["+ 界限（目前最佳）", "0.561"],
                 ["論文 ResNet / CDWC / CDCNN", "0.634 / 0.670 / 0.723"]],
                col_widths=[0.6, 0.4], highlight=(3, 6),
                note="0.460 → 0.561，全部來自正規化，不是來自 CDCNN 的任何一個元件。")

    table_slide(prs, "輸入修好後，CDCNN 元件仍然無效",
                ["消融步驟", "未正規化輸入", "逐樣本正規化輸入"],
                [["界限 + 梯度裁剪", "−0.0022", "+0.0044"],
                 ["增強 + 特徵生成", "−0.0328", "−0.0224"],
                 ["對比損失", "+0.0029", "−0.0049"]],
                col_widths=[0.4, 0.3, 0.3],
                note="輸入條件不是阻礙它們的原因。同時，逐樣本正規化讓完整 CDCNN 也提升 +0.0738（A3 0.460 → 0.534）。")

    content = content_slide(prs, "增強為什麼扣分：不是雜訊，是排程")
    bullets(content, [
        "雜訊縮小 20 倍（1.0 → 0.05），target mean 只變 +0.0026",
        ("零雜訊的純複製對照仍然扣 −0.0114（真實增強 −0.0131）", "key"),
        ("真正原因：增強 stage 有 890 筆而非 445 筆，在固定 100 epoch 下多了一倍的優化步數", "key"),
        "本專案（與原本 v6.3）所有「A1 對 B0」的比較都被排程長度混淆",
        "修正：每個 epoch 從增強池抽一份來源大小的子集，使步數對齊",
        "對齊本身 +0.0043；種子標準差從 0.0364 降到 0.0136（最穩定的一組）",
    ])

    table_slide(prs, "對比損失換到論文的位置：仍然是零",
                ["接法", "效果", "改善的種子"],
                [["我們的位置（FC128 後 + 可學 head）", "+0.0025", "3/5"],
                 ["論文的位置（FC128 前、無 head）", "+0.0002", "2/5"]],
                col_widths=[0.5, 0.25, 0.25],
                note="五次獨立量測（v6.3 / v6.5 / v6.6 / v6.9 / v6.10）全部落在 −0.005 ～ +0.003。"
                     "精確的說法：在本專案的 source-only 協定下與零無法區分——這不等於該機制本身無效。"
                     "論文的增益集中在 Toluene（0.27 → 0.92），而 τ、λ 與投影維度論文從未提供、本專案也從未調校。")

    # --- where the gap is --------------------------------------------------
    figure_slide(prs, "剩下的差距在哪：逐批次", FIG / "fig3_per_batch.png",
                 [("B2、B3、B4 已追平或贏過論文", "key"),
                  "B2：我們 0.89，論文 0.83",
                  ("差距集中在 B5–B10", "key"),
                  "B6：0.47 對 0.93",
                  "B8：0.27 對 0.72"])

    figure_slide(prs, "剩下的差距在哪：逐類別", FIG / "fig4_class_recall.png",
                 [("Ethylene 九批全部 0.00", "key"),
                  "9530 個樣本零命中，模型從不輸出這個標籤",
                  ("Ammonia、Toluene 撐到 B5 之後崩潰", "key"),
                  "三類佔每個目標批次的 26–66%"],
                 kicker="註：本專案原文件的氣體標籤對應有誤，已依論文 Table 2 逐批次比對更正（十批中八批完全吻合）")

    figure_slide(prs, "錯誤流向哪裡", FIG / "fig5_confusion.png",
                 [("B6：Toluene 98% 被判成 Acetone", "key"),
                  "Ammonia 40% 判成 Ethanol",
                  ("B8：Ammonia 68% 判成 Ethanol", "key"),
                  "Toluene 92% 判成 Acetone",
                  "預測分布偏向 Batch 1 的大類別：Acetone 被預測的頻率是實際的 2.4 倍"])

    table_slide(prs, "類別平衡：粗篩後否決",
                ["方式", "Batch 1 CV（Ethylene）", "目標（Ethylene）", "Target mean"],
                [["無平衡", "0.667", "0.000", "0.5521"],
                 ["類別加權", "0.800", "0.000", "0.5485"],
                 ["平衡取樣", "0.867", "0.000", "0.5454"]],
                kicker="一個種子、6 分鐘，取代五種子的 35 分鐘",
                col_widths=[0.28, 0.26, 0.23, 0.23], highlight=(2,),
                note="平衡在來源域完全有效，卻一點也沒傳遞到目標域：Ethylene 的問題是域偏移，不是類別不平衡。"
                     "協定警訊：Batch 1 CV 的排序與目標準確率完全相反——我們的協定用 CV 選模型，這次會選到最差的。")

    figure_slide(prs, "論文自己也有一個死掉的類別", FIG / "fig7_paper_confusion.png",
                 [("CDCNN 混淆矩陣有一列對角線是 0", "key"),
                  "比對他們的逐批次數字，最吻合的讀法是該類別就是 Ethylene",
                  "（推算 B6 = 0.93，論文報 0.9318）",
                  ("我們的 Ethylene 零命中是重現了他們的限制", "key"),
                  "真正的差距是 Ammonia（0.94）與 Toluene（0.92）",
                  "他們對比學習的增益幾乎就是 Toluene 一類"])

    # --- conclusions -------------------------------------------------------
    closing_slide(prs, "結論", [
        ("正規化是這個資料集上唯一有效的槓桿",
         "逐樣本輸入 +0.109、LayerNorm +0.085；模型從 0.460 提升到 0.561"),
        ("CDCNN 的三個機制在本協定下量不到貢獻",
         "對比損失五次獨立量測皆與零無法區分；這是特定協定與未調校超參數下的量測結果，不是一般性否定"),
        ("論文的宣稱有一部分無法重現，且論文自身也有一個完全失效的類別",
         "我們的 Ethylene 零命中重現了他們的限制；SVM 基線同樣為 0.002"),
        ("我們發現並修正了一個協定層級的混淆",
         "固定 epoch 數讓增強組多了一倍訓練步數，使所有 A1 對 B0 的比較失效"),
    ])

    table_slide(prs, "後續方向",
                ["優先", "方向", "理由"],
                [["1", "是什麼讓 Ammonia / Toluene 在 B5 後存活",
                  "論文的優勢與其對比消融的最大單類差異都在這裡"],
                 ["2", "對比超參數 τ、λ、投影維度",
                  "論文從未提供，本專案也從未調校；可只用 Batch 1 CV 選"],
                 ["3", "其餘數值忠實度項目", "σ′ 高斯取樣、Eq. (16) 的分母、Block 5 的 512 寬"],
                 ["4", "epoch 協定的正式決定", "對齊與不對齊各自固定不同的量，需要明確選一個"]],
                col_widths=[0.08, 0.37, 0.55])

    content = content_slide(prs, "附錄：結果可信度")
    bullets(content, [
        ("每次改動前都把所有既有 stage 用新舊程式碼各訓練一次，要求 bit-identical", "key"),
        "最後一次檢查涵蓋 26 個 stage，全部相同",
        "設定檔以凍結字面值固定其階段清單；驗證器兩次擋下會破壞既有執行的編輯",
        "同環境內完全可重現；跨 torch 版本 CV 相同、target mean 可能差在小數第四位",
        "每次執行自帶洩漏稽核，目標批次一律在凍結後才載入",
        "訓練環境固定為容器（torch 2.5.1+cu121），起因是一次 Xid 31 GPU 故障",
        ("過程中四次失誤均已記錄：session 中斷、報告產生器 KeyError、heredoc 引號、GPU 故障", "sub"),
    ])

    prs.save(OUT)
    print(f"wrote {OUT.relative_to(ROOT)} with {len(prs.slides._sldIdLst)} slides")


if __name__ == "__main__":
    build()
